### ISSUE TITLE
App Engine enables use of tags in provisioner manifests

### ISSUE THREAD

**Issue by robblovell** [c6o/provisioners#113]
### Business Requirements:
So that developers can control updates of their application, we need to have the App Engine honour templating of a tag in the provisioner section of the edition manifest.

```
      provisioner:
        name: echoserver
        tag: 2.1
        tag-prefix: appengine
        package: '@provisioner/appengine'
        image: 'robblovell/echo-server:{{tag}}'
        automated: true
        port:
```
### User Story:
As a developer
I want to use a tag to specify what version represents this edition
So that I can update customer's installs.

### Acceptance Criteria:
1. Given a provisioner manifest
When a tag is available with a templated image
Then the provisioner inserts the tag into the image name using the tag given.
