### ISSUE TITLE
chore: The NextCloud provisioner uses MySql as a dependency service

### ISSUE THREAD

**Issue by nsainaney** [c6o/provisioners#205]
### Background:
The provisioner manager allows for dependency services to be defined under:

```yaml
spec:
  provisioner:
    services:
      mysql: ... 
```

### Requirements:

- [ ] Update the nextcloud app manifest to include the mysql service
- [ ] Test using `czctl install`
- [ ] Expect to see nextcloud running with the mysql dependency service
- [ ] Uninstall nextcloud and ensure that mysql is also removed
